name: keras-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.3.2
  - pip:
    - tensorflow==2.15.0
    - numpy==1.23.5
    - pandas==1.3.5
    - flask==2.3.1
    - azureml-defaults==1.59.0
    - Werkzeug==3.1.*
    # Let AzureML manage gunicorn version